# Generated by Django 4.1.7 on 2023-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='test',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
