# Generated by Django 4.1.7 on 2023-04-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='test',
        ),
    ]
